//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by: EnumGenerator.Core - 3.2.1196.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

[GeneratedCode("EnumGenerator.Core", "3.2.1196.0")]
public enum Units
{
    HesthargTheEpic = 10,

    HalranTheSweet = 20,

    NewaruTheCool = 30,

    FledtheTheDude = 40,

    RistanTheStuff = 50,

    NkeleTheWarrior = 60,

    RaktrargTheMage = 70,

    HukrolmTheElf = 80,

    ConnchopTheOrk = 90,

    OrdhesTheWizard = 100,

    OdrudTheHandmaiden = 110,

    NeeaTheMagnificent = 120,

    CuthodTheEpic = 130,

    ChopneonTheRock = 140,

    TycromTheUberLord = 150,

    KahvortheonTheThinker = 160,

    LeofunTheDwarf = 170,

    HildahildaTheFool = 180,

    CynranTheBrains = 190,

    ThebeorthTheMechanic = 200,
}
